---
# Main tasks file for the mpx.ruby role

- name: Ensure make is installed (needed to install ruby_install)
  apt:
    name: make
    state: present
    update_cache: yes

# Installs the ruby-install tool:
- include: ruby_install.yml

# Installs ruby itself (from source):
- include: ruby.yml
