---
# Main tasks file for the mediafellows.ruby role

- name: Ensure make is installed (needed to install ruby_install)
  become: true
  ansible.builtin.apt:
    name: make
    state: present
    update_cache: yes

# Installs the ruby-install tool:
- ansible.builtin.import_tasks: ruby_install.yml

# Installs ruby itself (from source):
- ansible.builtin.import_tasks: ruby.yml
