---
# Main tasks file for the mpx.ruby role

- name: Ensure make is installed (needed to install ruby_install)
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - make

# Installs the ruby-install tool:
- include: ruby_install.yml

# Installs ruby itself (from source):
- include: ruby.yml
