---
# Installs the ruby-install tool that makes installing ruby from source much easier
# it takes care of finding the download source, checksumming the download, unpacking and compiling
# See https://github.com/postmodern/ruby-install for more details

- name: Download ruby-install
  ansible.builtin.get_url:
    url: https://github.com/postmodern/ruby-install/archive/v{{ ruby_install_version }}.tar.gz
    dest: "{{ ansible_env.HOME }}/ruby-install-{{ ruby_install_version }}.tar.gz"
  when:
    ansible_local is not defined or
    ansible_local.ruby_install is not defined or
    ansible_local.ruby_install.version != ruby_install_version
  register: ruby_install_downloaded

- name: Extract ruby-install
  ansible.builtin.unarchive:
    copy: no
    src: "{{ ansible_env.HOME }}/ruby-install-{{ ruby_install_version }}.tar.gz"
    dest: "{{ ansible_env.HOME }}"
  when: ruby_install_downloaded is changed

- name: Install ruby-install
  become: true
  ansible.builtin.shell:
    cmd: make install
    chdir: "{{ ansible_env.HOME }}/ruby-install-{{ ruby_install_version }}"
  when: ruby_install_downloaded is changed
  register: ruby_install_installed

- name: Clean up ruby-install sources
  ansible.builtin.shell:
    cmd: rm -rf {{ ansible_env.HOME }}/ruby-install-*
  when: ruby_install_downloaded is changed

# Setup ruby-install facts.d

- name: Capture installed ruby-install version
  ansible.builtin.shell:
    cmd: ruby-install --version | awk '{ print $2 }'
  ignore_errors: yes
  register: installed_ruby_install_version

- name: Create ansible facts directory
  become: true
  ansible.builtin.file:
    state: directory
    recurse: yes
    path: /etc/ansible/facts.d

- name: Set ruby-install facts
  become: true
  ansible.builtin.template:
    src: ruby_install.fact
    dest: /etc/ansible/facts.d/ruby_install.fact
